name: geo
channels:
  - conda-forge
dependencies:
  - python=3.8.6
  - geopandas=0.8.2
  - momepy=0.4.2
  - seaborn=0.11.1
  - pygeos=0.8
  - scikit-learn=0.24.1
  - contextily=1.1.0
  - legendgram=0.0.3
  - pysal=2.3.0
  - osmnx=1.0.1
  - scipy=1.6.0
  - clustergram=0.3.0
  - dask=2021.1.1